// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * GraphQLRequest
 */
export type GraphQlRequest = {
    /**
     * Query
     */
    query: string;
    /**
     * Variables
     */
    variables?: {
        [key: string]: unknown;
    } | null;
    /**
     * Operation Name
     */
    operation_name?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MapDetail
 */
export type MapDetail = {
    /**
     * Id
     *
     * 脑图唯一标识
     */
    id?: number | null;
    /**
     * Title
     *
     * 脑图标题
     */
    title: string;
    /**
     * Version
     *
     * 树版本号，每次内容变更递增（收放等视图态不递增）；客户端重连时对比版本决定是否全量重拉
     */
    version?: number;
    /**
     * Created At
     *
     * 创建时间（UTC）
     */
    created_at?: string;
    /**
     * Nodes
     */
    nodes?: Array<NodeDto>;
};

/**
 * MapSummary
 */
export type MapSummary = {
    /**
     * Id
     *
     * 脑图唯一标识
     */
    id?: number | null;
    /**
     * Title
     *
     * 脑图标题
     */
    title: string;
    /**
     * Version
     *
     * 树版本号，每次内容变更递增（收放等视图态不递增）；客户端重连时对比版本决定是否全量重拉
     */
    version?: number;
    /**
     * Created At
     *
     * 创建时间（UTC）
     */
    created_at?: string;
};

/**
 * MindmapServiceAddNodeRequest
 */
export type MindmapServiceAddNodeRequest = {
    /**
     * Map Id
     */
    map_id: number;
    /**
     * Parent Id
     */
    parent_id: number;
    /**
     * Content
     */
    content: string;
    /**
     * Position
     */
    position?: number | null;
    /**
     * Actor
     */
    actor?: string;
    /**
     * Source
     */
    source?: string | null;
};

/**
 * MindmapServiceApplyOutlineRequest
 */
export type MindmapServiceApplyOutlineRequest = {
    /**
     * Map Id
     */
    map_id: number;
    /**
     * Outline
     */
    outline: string;
    /**
     * Mode
     */
    mode?: string;
    /**
     * Actor
     */
    actor?: string;
    /**
     * Source
     */
    source?: string | null;
};

/**
 * MindmapServiceCreateMapRequest
 */
export type MindmapServiceCreateMapRequest = {
    /**
     * Title
     */
    title: string;
    /**
     * Actor
     */
    actor?: string;
    /**
     * Source
     */
    source?: string | null;
};

/**
 * MindmapServiceDeleteMapRequest
 */
export type MindmapServiceDeleteMapRequest = {
    /**
     * Map Id
     */
    map_id: number;
    /**
     * Actor
     */
    actor?: string;
    /**
     * Source
     */
    source?: string | null;
};

/**
 * MindmapServiceDeleteNodeRequest
 */
export type MindmapServiceDeleteNodeRequest = {
    /**
     * Map Id
     */
    map_id: number;
    /**
     * Node Id
     */
    node_id: number;
    /**
     * Actor
     */
    actor?: string;
    /**
     * Source
     */
    source?: string | null;
};

/**
 * MindmapServiceExpandAllRequest
 */
export type MindmapServiceExpandAllRequest = {
    /**
     * Map Id
     */
    map_id: number;
    /**
     * Actor
     */
    actor?: string;
    /**
     * Client Request Id
     */
    client_request_id?: string | null;
    /**
     * Source
     */
    source?: string | null;
};

/**
 * MindmapServiceGetMapRequest
 */
export type MindmapServiceGetMapRequest = {
    /**
     * Map Id
     */
    map_id: number;
};

/**
 * MindmapServiceGetRevisionRequest
 */
export type MindmapServiceGetRevisionRequest = {
    /**
     * Map Id
     */
    map_id: number;
    /**
     * Version
     */
    version: number;
};

/**
 * MindmapServiceGetTreeRequest
 */
export type MindmapServiceGetTreeRequest = {
    /**
     * Map Id
     */
    map_id: number;
};

/**
 * MindmapServiceListRevisionsRequest
 */
export type MindmapServiceListRevisionsRequest = {
    /**
     * Map Id
     */
    map_id: number;
};

/**
 * MindmapServiceMoveNodeRequest
 */
export type MindmapServiceMoveNodeRequest = {
    /**
     * Map Id
     */
    map_id: number;
    /**
     * Node Id
     */
    node_id: number;
    /**
     * New Parent Id
     */
    new_parent_id: number;
    /**
     * Position
     */
    position?: number | null;
    /**
     * Actor
     */
    actor?: string;
    /**
     * Source
     */
    source?: string | null;
};

/**
 * MindmapServiceRestoreRevisionRequest
 */
export type MindmapServiceRestoreRevisionRequest = {
    /**
     * Map Id
     */
    map_id: number;
    /**
     * Version
     */
    version: number;
    /**
     * Actor
     */
    actor?: string;
    /**
     * Source
     */
    source?: string | null;
};

/**
 * MindmapServiceSetFoldLevelRequest
 */
export type MindmapServiceSetFoldLevelRequest = {
    /**
     * Map Id
     */
    map_id: number;
    /**
     * Level
     */
    level: number;
    /**
     * Actor
     */
    actor?: string;
    /**
     * Client Request Id
     */
    client_request_id?: string | null;
    /**
     * Source
     */
    source?: string | null;
};

/**
 * MindmapServiceSetNodeCollapsedRequest
 */
export type MindmapServiceSetNodeCollapsedRequest = {
    /**
     * Map Id
     */
    map_id: number;
    /**
     * Node Id
     */
    node_id: number;
    /**
     * Collapsed
     */
    collapsed: boolean;
    /**
     * Actor
     */
    actor?: string;
    /**
     * Client Request Id
     */
    client_request_id?: string | null;
    /**
     * Source
     */
    source?: string | null;
};

/**
 * MindmapServiceUpdateNodeRequest
 */
export type MindmapServiceUpdateNodeRequest = {
    /**
     * Map Id
     */
    map_id: number;
    /**
     * Node Id
     */
    node_id: number;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Collapsed
     */
    collapsed?: boolean | null;
    /**
     * Actor
     */
    actor?: string;
    /**
     * Source
     */
    source?: string | null;
};

/**
 * NodeDTO
 */
export type NodeDto = {
    /**
     * Display Id
     *
     * map 内节点编号，每图从 1 起；对外接口与 outline 协议的唯一 ID 语义
     */
    display_id: number;
    /**
     * Map Id
     *
     * 所属脑图 ID
     */
    map_id: number;
    /**
     * Parent Id
     *
     * 父节点全局主键（内部使用）；根节点为 None（每棵 Map 恰有一个根节点）
     */
    parent_id?: number | null;
    /**
     * Content
     *
     * 节点文本内容
     */
    content: string;
    /**
     * Position
     *
     * 同级节点中的排序序号，越小越靠前
     */
    position?: number;
    /**
     * Collapsed
     *
     * 前端折叠状态：True 时子树在界面上收起
     */
    collapsed?: boolean;
    /**
     * Updated By
     *
     * 最后修改者来源：'human'（浏览器编辑）或 'agent'（CLI/MCP/REST 修改）
     */
    updated_by?: string;
    /**
     * Updated At
     *
     * 最后修改时间（UTC），每次内容变更刷新
     */
    updated_at?: string;
    parent?: NodeRef | null;
};

/**
 * NodeRef
 */
export type NodeRef = {
    /**
     * Display Id
     *
     * map 内节点编号，每图从 1 起；对外接口与 outline 协议的唯一 ID 语义
     */
    display_id: number;
};

/**
 * RevisionDetail
 */
export type RevisionDetail = {
    /**
     * Id
     *
     * 快照行主键
     */
    id?: number | null;
    /**
     * Map Id
     *
     * 所属脑图 ID
     */
    map_id: number;
    /**
     * Version
     *
     * 该快照对应的树版本号（mutation 提交后的 version）
     */
    version: number;
    /**
     * Action
     *
     * 产生该版本的动作：'map_created' / 'node_added' / … / 'revision_restored'
     */
    action: string;
    /**
     * Actor
     *
     * 动作来源：'human'（浏览器）或 'agent'（CLI/MCP/REST）
     */
    actor?: string;
    /**
     * Detail
     *
     * 人类可读改动摘要（时间线展示用，与 publish_change 的 detail 同文）
     */
    detail?: string | null;
    /**
     * Created At
     *
     * 快照产生时间（UTC）
     */
    created_at?: string;
    snapshot: RevisionSnapshotDto;
};

/**
 * RevisionNodeDTO
 *
 * 快照内的节点（display_id 语义：parent 是父节点 display_id，根为 None）。
 */
export type RevisionNodeDto = {
    /**
     * Display Id
     */
    display_id: number;
    /**
     * Parent
     */
    parent: number | null;
    /**
     * Content
     */
    content: string;
    /**
     * Position
     */
    position: number;
    /**
     * Collapsed
     */
    collapsed: boolean;
    /**
     * Updated By
     */
    updated_by: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * RevisionSnapshotDTO
 *
 * 整树快照（模型层存 sa.JSON dict，DTO 层转嵌套模型——compose schema
 * 不支持裸 dict，Pydantic 嵌套模型同时让 GraphQL 面成为结构化类型）。
 */
export type RevisionSnapshotDto = {
    /**
     * Title
     */
    title: string;
    /**
     * Nodes
     */
    nodes: Array<RevisionNodeDto>;
};

/**
 * RevisionSummary
 */
export type RevisionSummary = {
    /**
     * Id
     *
     * 快照行主键
     */
    id?: number | null;
    /**
     * Map Id
     *
     * 所属脑图 ID
     */
    map_id: number;
    /**
     * Version
     *
     * 该快照对应的树版本号（mutation 提交后的 version）
     */
    version: number;
    /**
     * Action
     *
     * 产生该版本的动作：'map_created' / 'node_added' / … / 'revision_restored'
     */
    action: string;
    /**
     * Actor
     *
     * 动作来源：'human'（浏览器）或 'agent'（CLI/MCP/REST）
     */
    actor?: string;
    /**
     * Detail
     *
     * 人类可读改动摘要（时间线展示用，与 publish_change 的 detail 同文）
     */
    detail?: string | null;
    /**
     * Created At
     *
     * 快照产生时间（UTC）
     */
    created_at?: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type HandlerApiMindmapServiceListMapsPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/list_maps';
};

export type HandlerApiMindmapServiceListMapsPostResponses = {
    /**
     * Response Handler Api Mindmap Service List Maps Post
     *
     * Successful Response
     */
    200: Array<MapSummary>;
};

export type HandlerApiMindmapServiceListMapsPostResponse = HandlerApiMindmapServiceListMapsPostResponses[keyof HandlerApiMindmapServiceListMapsPostResponses];

export type HandlerApiMindmapServiceGetMapPostData = {
    body: MindmapServiceGetMapRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/get_map';
};

export type HandlerApiMindmapServiceGetMapPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HandlerApiMindmapServiceGetMapPostError = HandlerApiMindmapServiceGetMapPostErrors[keyof HandlerApiMindmapServiceGetMapPostErrors];

export type HandlerApiMindmapServiceGetMapPostResponses = {
    /**
     * Successful Response
     */
    200: MapDetail;
};

export type HandlerApiMindmapServiceGetMapPostResponse = HandlerApiMindmapServiceGetMapPostResponses[keyof HandlerApiMindmapServiceGetMapPostResponses];

export type HandlerApiMindmapServiceGetTreePostData = {
    body: MindmapServiceGetTreeRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/get_tree';
};

export type HandlerApiMindmapServiceGetTreePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HandlerApiMindmapServiceGetTreePostError = HandlerApiMindmapServiceGetTreePostErrors[keyof HandlerApiMindmapServiceGetTreePostErrors];

export type HandlerApiMindmapServiceGetTreePostResponses = {
    /**
     * Response Handler Api Mindmap Service Get Tree Post
     *
     * Successful Response
     */
    200: string;
};

export type HandlerApiMindmapServiceGetTreePostResponse = HandlerApiMindmapServiceGetTreePostResponses[keyof HandlerApiMindmapServiceGetTreePostResponses];

export type HandlerApiMindmapServiceListRevisionsPostData = {
    body: MindmapServiceListRevisionsRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/list_revisions';
};

export type HandlerApiMindmapServiceListRevisionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HandlerApiMindmapServiceListRevisionsPostError = HandlerApiMindmapServiceListRevisionsPostErrors[keyof HandlerApiMindmapServiceListRevisionsPostErrors];

export type HandlerApiMindmapServiceListRevisionsPostResponses = {
    /**
     * Response Handler Api Mindmap Service List Revisions Post
     *
     * Successful Response
     */
    200: Array<RevisionSummary>;
};

export type HandlerApiMindmapServiceListRevisionsPostResponse = HandlerApiMindmapServiceListRevisionsPostResponses[keyof HandlerApiMindmapServiceListRevisionsPostResponses];

export type HandlerApiMindmapServiceGetRevisionPostData = {
    body: MindmapServiceGetRevisionRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/get_revision';
};

export type HandlerApiMindmapServiceGetRevisionPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HandlerApiMindmapServiceGetRevisionPostError = HandlerApiMindmapServiceGetRevisionPostErrors[keyof HandlerApiMindmapServiceGetRevisionPostErrors];

export type HandlerApiMindmapServiceGetRevisionPostResponses = {
    /**
     * Successful Response
     */
    200: RevisionDetail;
};

export type HandlerApiMindmapServiceGetRevisionPostResponse = HandlerApiMindmapServiceGetRevisionPostResponses[keyof HandlerApiMindmapServiceGetRevisionPostResponses];

export type HandlerApiMindmapServiceCreateMapPostData = {
    body: MindmapServiceCreateMapRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/create_map';
};

export type HandlerApiMindmapServiceCreateMapPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HandlerApiMindmapServiceCreateMapPostError = HandlerApiMindmapServiceCreateMapPostErrors[keyof HandlerApiMindmapServiceCreateMapPostErrors];

export type HandlerApiMindmapServiceCreateMapPostResponses = {
    /**
     * Successful Response
     */
    200: MapDetail;
};

export type HandlerApiMindmapServiceCreateMapPostResponse = HandlerApiMindmapServiceCreateMapPostResponses[keyof HandlerApiMindmapServiceCreateMapPostResponses];

export type HandlerApiMindmapServiceAddNodePostData = {
    body: MindmapServiceAddNodeRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/add_node';
};

export type HandlerApiMindmapServiceAddNodePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HandlerApiMindmapServiceAddNodePostError = HandlerApiMindmapServiceAddNodePostErrors[keyof HandlerApiMindmapServiceAddNodePostErrors];

export type HandlerApiMindmapServiceAddNodePostResponses = {
    /**
     * Successful Response
     */
    200: NodeDto;
};

export type HandlerApiMindmapServiceAddNodePostResponse = HandlerApiMindmapServiceAddNodePostResponses[keyof HandlerApiMindmapServiceAddNodePostResponses];

export type HandlerApiMindmapServiceUpdateNodePostData = {
    body: MindmapServiceUpdateNodeRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/update_node';
};

export type HandlerApiMindmapServiceUpdateNodePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HandlerApiMindmapServiceUpdateNodePostError = HandlerApiMindmapServiceUpdateNodePostErrors[keyof HandlerApiMindmapServiceUpdateNodePostErrors];

export type HandlerApiMindmapServiceUpdateNodePostResponses = {
    /**
     * Successful Response
     */
    200: NodeDto;
};

export type HandlerApiMindmapServiceUpdateNodePostResponse = HandlerApiMindmapServiceUpdateNodePostResponses[keyof HandlerApiMindmapServiceUpdateNodePostResponses];

export type HandlerApiMindmapServiceSetNodeCollapsedPostData = {
    body: MindmapServiceSetNodeCollapsedRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/set_node_collapsed';
};

export type HandlerApiMindmapServiceSetNodeCollapsedPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HandlerApiMindmapServiceSetNodeCollapsedPostError = HandlerApiMindmapServiceSetNodeCollapsedPostErrors[keyof HandlerApiMindmapServiceSetNodeCollapsedPostErrors];

export type HandlerApiMindmapServiceSetNodeCollapsedPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type HandlerApiMindmapServiceSetNodeCollapsedPostResponse = HandlerApiMindmapServiceSetNodeCollapsedPostResponses[keyof HandlerApiMindmapServiceSetNodeCollapsedPostResponses];

export type HandlerApiMindmapServiceMoveNodePostData = {
    body: MindmapServiceMoveNodeRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/move_node';
};

export type HandlerApiMindmapServiceMoveNodePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HandlerApiMindmapServiceMoveNodePostError = HandlerApiMindmapServiceMoveNodePostErrors[keyof HandlerApiMindmapServiceMoveNodePostErrors];

export type HandlerApiMindmapServiceMoveNodePostResponses = {
    /**
     * Successful Response
     */
    200: NodeDto;
};

export type HandlerApiMindmapServiceMoveNodePostResponse = HandlerApiMindmapServiceMoveNodePostResponses[keyof HandlerApiMindmapServiceMoveNodePostResponses];

export type HandlerApiMindmapServiceDeleteNodePostData = {
    body: MindmapServiceDeleteNodeRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/delete_node';
};

export type HandlerApiMindmapServiceDeleteNodePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HandlerApiMindmapServiceDeleteNodePostError = HandlerApiMindmapServiceDeleteNodePostErrors[keyof HandlerApiMindmapServiceDeleteNodePostErrors];

export type HandlerApiMindmapServiceDeleteNodePostResponses = {
    /**
     * Response Handler Api Mindmap Service Delete Node Post
     *
     * Successful Response
     */
    200: boolean;
};

export type HandlerApiMindmapServiceDeleteNodePostResponse = HandlerApiMindmapServiceDeleteNodePostResponses[keyof HandlerApiMindmapServiceDeleteNodePostResponses];

export type HandlerApiMindmapServiceDeleteMapPostData = {
    body: MindmapServiceDeleteMapRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/delete_map';
};

export type HandlerApiMindmapServiceDeleteMapPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HandlerApiMindmapServiceDeleteMapPostError = HandlerApiMindmapServiceDeleteMapPostErrors[keyof HandlerApiMindmapServiceDeleteMapPostErrors];

export type HandlerApiMindmapServiceDeleteMapPostResponses = {
    /**
     * Response Handler Api Mindmap Service Delete Map Post
     *
     * Successful Response
     */
    200: boolean;
};

export type HandlerApiMindmapServiceDeleteMapPostResponse = HandlerApiMindmapServiceDeleteMapPostResponses[keyof HandlerApiMindmapServiceDeleteMapPostResponses];

export type HandlerApiMindmapServiceRestoreRevisionPostData = {
    body: MindmapServiceRestoreRevisionRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/restore_revision';
};

export type HandlerApiMindmapServiceRestoreRevisionPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HandlerApiMindmapServiceRestoreRevisionPostError = HandlerApiMindmapServiceRestoreRevisionPostErrors[keyof HandlerApiMindmapServiceRestoreRevisionPostErrors];

export type HandlerApiMindmapServiceRestoreRevisionPostResponses = {
    /**
     * Successful Response
     */
    200: MapDetail;
};

export type HandlerApiMindmapServiceRestoreRevisionPostResponse = HandlerApiMindmapServiceRestoreRevisionPostResponses[keyof HandlerApiMindmapServiceRestoreRevisionPostResponses];

export type HandlerApiMindmapServiceExpandAllPostData = {
    body: MindmapServiceExpandAllRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/expand_all';
};

export type HandlerApiMindmapServiceExpandAllPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HandlerApiMindmapServiceExpandAllPostError = HandlerApiMindmapServiceExpandAllPostErrors[keyof HandlerApiMindmapServiceExpandAllPostErrors];

export type HandlerApiMindmapServiceExpandAllPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type HandlerApiMindmapServiceExpandAllPostResponse = HandlerApiMindmapServiceExpandAllPostResponses[keyof HandlerApiMindmapServiceExpandAllPostResponses];

export type HandlerApiMindmapServiceSetFoldLevelPostData = {
    body: MindmapServiceSetFoldLevelRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/set_fold_level';
};

export type HandlerApiMindmapServiceSetFoldLevelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HandlerApiMindmapServiceSetFoldLevelPostError = HandlerApiMindmapServiceSetFoldLevelPostErrors[keyof HandlerApiMindmapServiceSetFoldLevelPostErrors];

export type HandlerApiMindmapServiceSetFoldLevelPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type HandlerApiMindmapServiceSetFoldLevelPostResponse = HandlerApiMindmapServiceSetFoldLevelPostResponses[keyof HandlerApiMindmapServiceSetFoldLevelPostResponses];

export type HandlerApiMindmapServiceApplyOutlinePostData = {
    body: MindmapServiceApplyOutlineRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/apply_outline';
};

export type HandlerApiMindmapServiceApplyOutlinePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HandlerApiMindmapServiceApplyOutlinePostError = HandlerApiMindmapServiceApplyOutlinePostErrors[keyof HandlerApiMindmapServiceApplyOutlinePostErrors];

export type HandlerApiMindmapServiceApplyOutlinePostResponses = {
    /**
     * Successful Response
     */
    200: MapDetail;
};

export type HandlerApiMindmapServiceApplyOutlinePostResponse = HandlerApiMindmapServiceApplyOutlinePostResponses[keyof HandlerApiMindmapServiceApplyOutlinePostResponses];

export type GraphiqlGraphqlGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/graphql';
};

export type GraphiqlGraphqlGetResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type GraphiqlGraphqlGetResponse = GraphiqlGraphqlGetResponses[keyof GraphiqlGraphqlGetResponses];

export type GraphqlEndpointGraphqlPostData = {
    body: GraphQlRequest;
    path?: never;
    query?: never;
    url: '/graphql';
};

export type GraphqlEndpointGraphqlPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GraphqlEndpointGraphqlPostError = GraphqlEndpointGraphqlPostErrors[keyof GraphqlEndpointGraphqlPostErrors];

export type GraphqlEndpointGraphqlPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GraphqlSchemaSchemaGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/schema';
};

export type GraphqlSchemaSchemaGetResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type GraphqlSchemaSchemaGetResponse = GraphqlSchemaSchemaGetResponses[keyof GraphqlSchemaSchemaGetResponses];

export type ChatArchivesApiChatArchivesGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Map Id
         */
        map_id: number;
    };
    url: '/api/chat/archives';
};

export type ChatArchivesApiChatArchivesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatArchivesApiChatArchivesGetError = ChatArchivesApiChatArchivesGetErrors[keyof ChatArchivesApiChatArchivesGetErrors];

export type ChatArchivesApiChatArchivesGetResponses = {
    /**
     * Response Chat Archives Api Chat Archives Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type ChatArchivesApiChatArchivesGetResponse = ChatArchivesApiChatArchivesGetResponses[keyof ChatArchivesApiChatArchivesGetResponses];

export type ChatArchiveDetailApiChatArchivesArchiveIdGetData = {
    body?: never;
    path: {
        /**
         * Archive Id
         */
        archive_id: string;
    };
    query: {
        /**
         * Map Id
         */
        map_id: number;
    };
    url: '/api/chat/archives/{archive_id}';
};

export type ChatArchiveDetailApiChatArchivesArchiveIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatArchiveDetailApiChatArchivesArchiveIdGetError = ChatArchiveDetailApiChatArchivesArchiveIdGetErrors[keyof ChatArchiveDetailApiChatArchivesArchiveIdGetErrors];

export type ChatArchiveDetailApiChatArchivesArchiveIdGetResponses = {
    /**
     * Response Chat Archive Detail Api Chat Archives  Archive Id  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ChatArchiveDetailApiChatArchivesArchiveIdGetResponse = ChatArchiveDetailApiChatArchivesArchiveIdGetResponses[keyof ChatArchiveDetailApiChatArchivesArchiveIdGetResponses];

export type ChatStatusApiChatStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/chat/status';
};

export type ChatStatusApiChatStatusGetResponses = {
    /**
     * Response Chat Status Api Chat Status Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ChatStatusApiChatStatusGetResponse = ChatStatusApiChatStatusGetResponses[keyof ChatStatusApiChatStatusGetResponses];
