// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * GraphQLRequest
 */
export type GraphQlRequest = {
    /**
     * Query
     */
    query: string;
    /**
     * Variables
     */
    variables?: {
        [key: string]: unknown;
    } | null;
    /**
     * Operation Name
     */
    operation_name?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MapDetail
 */
export type MapDetail = {
    /**
     * Id
     *
     * 脑图唯一标识
     */
    id?: number | null;
    /**
     * Title
     *
     * 脑图标题
     */
    title: string;
    /**
     * Version
     *
     * 树版本号，每次内容变更递增（收放等视图态不递增）；客户端重连时对比版本决定是否全量重拉
     */
    version?: number;
    /**
     * Created At
     *
     * 创建时间（UTC）
     */
    created_at?: string;
    /**
     * Nodes
     */
    nodes?: Array<NodeDto>;
};

/**
 * MapSummary
 */
export type MapSummary = {
    /**
     * Id
     *
     * 脑图唯一标识
     */
    id?: number | null;
    /**
     * Title
     *
     * 脑图标题
     */
    title: string;
    /**
     * Version
     *
     * 树版本号，每次内容变更递增（收放等视图态不递增）；客户端重连时对比版本决定是否全量重拉
     */
    version?: number;
    /**
     * Created At
     *
     * 创建时间（UTC）
     */
    created_at?: string;
};

/**
 * MindmapServiceAddNodeRequest
 */
export type MindmapServiceAddNodeRequest = {
    /**
     * Map Id
     */
    map_id: number;
    /**
     * Parent Id
     */
    parent_id: number;
    /**
     * Content
     */
    content: string;
    /**
     * Position
     */
    position?: number | null;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Actor
     */
    actor?: string;
};

/**
 * MindmapServiceApplyOutlineRequest
 */
export type MindmapServiceApplyOutlineRequest = {
    /**
     * Map Id
     */
    map_id: number;
    /**
     * Outline
     */
    outline: string;
    /**
     * Mode
     */
    mode?: string;
    /**
     * Actor
     */
    actor?: string;
};

/**
 * MindmapServiceCreateMapRequest
 */
export type MindmapServiceCreateMapRequest = {
    /**
     * Title
     */
    title: string;
    /**
     * Actor
     */
    actor?: string;
};

/**
 * MindmapServiceDeleteMapRequest
 */
export type MindmapServiceDeleteMapRequest = {
    /**
     * Map Id
     */
    map_id: number;
    /**
     * Actor
     */
    actor?: string;
};

/**
 * MindmapServiceDeleteNodeRequest
 */
export type MindmapServiceDeleteNodeRequest = {
    /**
     * Map Id
     */
    map_id: number;
    /**
     * Node Id
     */
    node_id: number;
    /**
     * Actor
     */
    actor?: string;
};

/**
 * MindmapServiceExpandAllRequest
 */
export type MindmapServiceExpandAllRequest = {
    /**
     * Map Id
     */
    map_id: number;
    /**
     * Actor
     */
    actor?: string;
    /**
     * Client Request Id
     */
    client_request_id?: string | null;
};

/**
 * MindmapServiceGetMapRequest
 */
export type MindmapServiceGetMapRequest = {
    /**
     * Map Id
     */
    map_id: number;
};

/**
 * MindmapServiceGetNodeRequest
 */
export type MindmapServiceGetNodeRequest = {
    /**
     * Map Id
     */
    map_id: number;
    /**
     * Node Id
     */
    node_id: number;
};

/**
 * MindmapServiceGetRevisionChangesRequest
 */
export type MindmapServiceGetRevisionChangesRequest = {
    /**
     * Map Id
     */
    map_id: number;
    /**
     * Version
     */
    version: number;
};

/**
 * MindmapServiceGetRevisionRequest
 */
export type MindmapServiceGetRevisionRequest = {
    /**
     * Map Id
     */
    map_id: number;
    /**
     * Version
     */
    version: number;
};

/**
 * MindmapServiceGetTreeRequest
 */
export type MindmapServiceGetTreeRequest = {
    /**
     * Map Id
     */
    map_id: number;
};

/**
 * MindmapServiceListRevisionsRequest
 */
export type MindmapServiceListRevisionsRequest = {
    /**
     * Map Id
     */
    map_id: number;
};

/**
 * MindmapServiceMoveNodeRequest
 */
export type MindmapServiceMoveNodeRequest = {
    /**
     * Map Id
     */
    map_id: number;
    /**
     * Node Id
     */
    node_id: number;
    /**
     * New Parent Id
     */
    new_parent_id: number;
    /**
     * Position
     */
    position?: number | null;
    /**
     * Actor
     */
    actor?: string;
};

/**
 * MindmapServiceRestoreRevisionRequest
 */
export type MindmapServiceRestoreRevisionRequest = {
    /**
     * Map Id
     */
    map_id: number;
    /**
     * Version
     */
    version: number;
    /**
     * Actor
     */
    actor?: string;
};

/**
 * MindmapServiceSetFoldLevelRequest
 */
export type MindmapServiceSetFoldLevelRequest = {
    /**
     * Map Id
     */
    map_id: number;
    /**
     * Level
     */
    level: number;
    /**
     * Actor
     */
    actor?: string;
    /**
     * Client Request Id
     */
    client_request_id?: string | null;
};

/**
 * MindmapServiceSetNodeCollapsedRequest
 */
export type MindmapServiceSetNodeCollapsedRequest = {
    /**
     * Map Id
     */
    map_id: number;
    /**
     * Node Id
     */
    node_id: number;
    /**
     * Collapsed
     */
    collapsed: boolean;
    /**
     * Actor
     */
    actor?: string;
    /**
     * Client Request Id
     */
    client_request_id?: string | null;
};

/**
 * MindmapServiceUpdateNodeRequest
 */
export type MindmapServiceUpdateNodeRequest = {
    /**
     * Map Id
     */
    map_id: number;
    /**
     * Node Id
     */
    node_id: number;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Collapsed
     */
    collapsed?: boolean | null;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Actor
     */
    actor?: string;
};

/**
 * NodeDTO
 */
export type NodeDto = {
    /**
     * Display Id
     *
     * map 内节点编号，每图从 1 起；对外接口与 outline 协议的唯一 ID 语义
     */
    display_id: number;
    /**
     * Map Id
     *
     * 所属脑图 ID
     */
    map_id: number;
    /**
     * Parent Id
     *
     * 父节点全局主键（内部使用）；根节点为 None（每棵 Map 恰有一个根节点）
     */
    parent_id?: number | null;
    /**
     * Content
     *
     * 节点文本内容
     */
    content: string;
    /**
     * Note
     *
     * 节点备注（markdown 长文，Agent 生成内容的主要落点）；null = 无备注，空串写入时归一为 null
     */
    note?: string | null;
    /**
     * Position
     *
     * 同级节点中的排序序号，越小越靠前
     */
    position?: number;
    /**
     * Collapsed
     *
     * 前端折叠状态：True 时子树在界面上收起
     */
    collapsed?: boolean;
    /**
     * Updated By
     *
     * 最后修改者来源：'human'（浏览器编辑）或 'agent'（CLI/MCP/REST 修改）
     */
    updated_by?: string;
    /**
     * Updated At
     *
     * 最后修改时间（UTC），每次内容变更刷新
     */
    updated_at?: string;
    parent?: NodeRef | null;
};

/**
 * NodeRef
 */
export type NodeRef = {
    /**
     * Display Id
     *
     * map 内节点编号，每图从 1 起；对外接口与 outline 协议的唯一 ID 语义
     */
    display_id: number;
};

/**
 * RevisionChangeRowDTO
 *
 * 版本间变更行：该版本相对上一版本，一个节点的一项变化。
 *
 * kind 语义（注意与旧"回滚预览"视角相反——这是该版本当时发生的事）：
 * added=本版新增 / removed=本版删除 / changed=标题改（old_content 为改前）
 * / note=备注改 / moved=换父 / folded=收放。
 */
export type RevisionChangeRowDto = {
    /**
     * Display Id
     */
    display_id: number;
    /**
     * Kind
     */
    kind: string;
    /**
     * Content
     */
    content: string;
    /**
     * Old Content
     */
    old_content?: string | null;
};

/**
 * RevisionChangesDTO
 *
 * 版本间变更集（get_revision_changes 返回体）。
 */
export type RevisionChangesDto = {
    /**
     * Title Change
     */
    title_change: boolean;
    /**
     * Old Title
     */
    old_title?: string | null;
    /**
     * Rows
     */
    rows: Array<RevisionChangeRowDto>;
};

/**
 * RevisionDetail
 */
export type RevisionDetail = {
    /**
     * Id
     *
     * 版本行主键
     */
    id?: number | null;
    /**
     * Map Id
     *
     * 所属脑图 ID
     */
    map_id: number;
    /**
     * Version
     *
     * 该版本对应的树版本号（mutation 提交后的 version）
     */
    version: number;
    /**
     * Action
     *
     * 产生该版本的动作：'map_created' / 'node_added' / … / 'revision_restored'
     */
    action: string;
    /**
     * Actor
     *
     * 动作来源：'human'（浏览器）或 'agent'（CLI/MCP/REST）
     */
    actor?: string;
    /**
     * Detail
     *
     * 人类可读改动摘要（时间线展示用，与 publish_change 的 detail 同文）
     */
    detail?: string | null;
    /**
     * Created At
     *
     * 版本产生时间（UTC）
     */
    created_at?: string;
    snapshot: RevisionSnapshotDto;
};

/**
 * RevisionNodeDTO
 *
 * 快照内的节点（display_id 语义：parent 是父节点 display_id，根为 None）。
 */
export type RevisionNodeDto = {
    /**
     * Display Id
     */
    display_id: number;
    /**
     * Parent
     */
    parent: number | null;
    /**
     * Content
     */
    content: string;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Position
     */
    position: number;
    /**
     * Collapsed
     */
    collapsed: boolean;
    /**
     * Updated By
     */
    updated_by: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * RevisionSnapshotDTO
 *
 * 整树快照（模型层存 sa.JSON dict，DTO 层转嵌套模型——compose schema
 * 不支持裸 dict，Pydantic 嵌套模型同时让 GraphQL 面成为结构化类型）。
 */
export type RevisionSnapshotDto = {
    /**
     * Title
     */
    title: string;
    /**
     * Nodes
     */
    nodes: Array<RevisionNodeDto>;
};

/**
 * RevisionSummary
 */
export type RevisionSummary = {
    /**
     * Id
     *
     * 版本行主键
     */
    id?: number | null;
    /**
     * Map Id
     *
     * 所属脑图 ID
     */
    map_id: number;
    /**
     * Version
     *
     * 该版本对应的树版本号（mutation 提交后的 version）
     */
    version: number;
    /**
     * Action
     *
     * 产生该版本的动作：'map_created' / 'node_added' / … / 'revision_restored'
     */
    action: string;
    /**
     * Actor
     *
     * 动作来源：'human'（浏览器）或 'agent'（CLI/MCP/REST）
     */
    actor?: string;
    /**
     * Detail
     *
     * 人类可读改动摘要（时间线展示用，与 publish_change 的 detail 同文）
     */
    detail?: string | null;
    /**
     * Created At
     *
     * 版本产生时间（UTC）
     */
    created_at?: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ListMapsApiMindmapServiceListMapsPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/list_maps';
};

export type ListMapsApiMindmapServiceListMapsPostResponses = {
    /**
     * Response List Maps Api Mindmap Service List Maps Post
     *
     * Successful Response
     */
    200: Array<MapSummary>;
};

export type ListMapsApiMindmapServiceListMapsPostResponse = ListMapsApiMindmapServiceListMapsPostResponses[keyof ListMapsApiMindmapServiceListMapsPostResponses];

export type GetMapApiMindmapServiceGetMapPostData = {
    body: MindmapServiceGetMapRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/get_map';
};

export type GetMapApiMindmapServiceGetMapPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMapApiMindmapServiceGetMapPostError = GetMapApiMindmapServiceGetMapPostErrors[keyof GetMapApiMindmapServiceGetMapPostErrors];

export type GetMapApiMindmapServiceGetMapPostResponses = {
    /**
     * Successful Response
     */
    200: MapDetail;
};

export type GetMapApiMindmapServiceGetMapPostResponse = GetMapApiMindmapServiceGetMapPostResponses[keyof GetMapApiMindmapServiceGetMapPostResponses];

export type GetTreeApiMindmapServiceGetTreePostData = {
    body: MindmapServiceGetTreeRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/get_tree';
};

export type GetTreeApiMindmapServiceGetTreePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTreeApiMindmapServiceGetTreePostError = GetTreeApiMindmapServiceGetTreePostErrors[keyof GetTreeApiMindmapServiceGetTreePostErrors];

export type GetTreeApiMindmapServiceGetTreePostResponses = {
    /**
     * Response Get Tree Api Mindmap Service Get Tree Post
     *
     * Successful Response
     */
    200: string;
};

export type GetTreeApiMindmapServiceGetTreePostResponse = GetTreeApiMindmapServiceGetTreePostResponses[keyof GetTreeApiMindmapServiceGetTreePostResponses];

export type GetNodeApiMindmapServiceGetNodePostData = {
    body: MindmapServiceGetNodeRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/get_node';
};

export type GetNodeApiMindmapServiceGetNodePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetNodeApiMindmapServiceGetNodePostError = GetNodeApiMindmapServiceGetNodePostErrors[keyof GetNodeApiMindmapServiceGetNodePostErrors];

export type GetNodeApiMindmapServiceGetNodePostResponses = {
    /**
     * Successful Response
     */
    200: NodeDto;
};

export type GetNodeApiMindmapServiceGetNodePostResponse = GetNodeApiMindmapServiceGetNodePostResponses[keyof GetNodeApiMindmapServiceGetNodePostResponses];

export type ListRevisionsApiMindmapServiceListRevisionsPostData = {
    body: MindmapServiceListRevisionsRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/list_revisions';
};

export type ListRevisionsApiMindmapServiceListRevisionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRevisionsApiMindmapServiceListRevisionsPostError = ListRevisionsApiMindmapServiceListRevisionsPostErrors[keyof ListRevisionsApiMindmapServiceListRevisionsPostErrors];

export type ListRevisionsApiMindmapServiceListRevisionsPostResponses = {
    /**
     * Response List Revisions Api Mindmap Service List Revisions Post
     *
     * Successful Response
     */
    200: Array<RevisionSummary>;
};

export type ListRevisionsApiMindmapServiceListRevisionsPostResponse = ListRevisionsApiMindmapServiceListRevisionsPostResponses[keyof ListRevisionsApiMindmapServiceListRevisionsPostResponses];

export type GetRevisionApiMindmapServiceGetRevisionPostData = {
    body: MindmapServiceGetRevisionRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/get_revision';
};

export type GetRevisionApiMindmapServiceGetRevisionPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRevisionApiMindmapServiceGetRevisionPostError = GetRevisionApiMindmapServiceGetRevisionPostErrors[keyof GetRevisionApiMindmapServiceGetRevisionPostErrors];

export type GetRevisionApiMindmapServiceGetRevisionPostResponses = {
    /**
     * Successful Response
     */
    200: RevisionDetail;
};

export type GetRevisionApiMindmapServiceGetRevisionPostResponse = GetRevisionApiMindmapServiceGetRevisionPostResponses[keyof GetRevisionApiMindmapServiceGetRevisionPostResponses];

export type GetRevisionChangesApiMindmapServiceGetRevisionChangesPostData = {
    body: MindmapServiceGetRevisionChangesRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/get_revision_changes';
};

export type GetRevisionChangesApiMindmapServiceGetRevisionChangesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRevisionChangesApiMindmapServiceGetRevisionChangesPostError = GetRevisionChangesApiMindmapServiceGetRevisionChangesPostErrors[keyof GetRevisionChangesApiMindmapServiceGetRevisionChangesPostErrors];

export type GetRevisionChangesApiMindmapServiceGetRevisionChangesPostResponses = {
    /**
     * Successful Response
     */
    200: RevisionChangesDto;
};

export type GetRevisionChangesApiMindmapServiceGetRevisionChangesPostResponse = GetRevisionChangesApiMindmapServiceGetRevisionChangesPostResponses[keyof GetRevisionChangesApiMindmapServiceGetRevisionChangesPostResponses];

export type CreateMapApiMindmapServiceCreateMapPostData = {
    body: MindmapServiceCreateMapRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/create_map';
};

export type CreateMapApiMindmapServiceCreateMapPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMapApiMindmapServiceCreateMapPostError = CreateMapApiMindmapServiceCreateMapPostErrors[keyof CreateMapApiMindmapServiceCreateMapPostErrors];

export type CreateMapApiMindmapServiceCreateMapPostResponses = {
    /**
     * Successful Response
     */
    200: MapDetail;
};

export type CreateMapApiMindmapServiceCreateMapPostResponse = CreateMapApiMindmapServiceCreateMapPostResponses[keyof CreateMapApiMindmapServiceCreateMapPostResponses];

export type AddNodeApiMindmapServiceAddNodePostData = {
    body: MindmapServiceAddNodeRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/add_node';
};

export type AddNodeApiMindmapServiceAddNodePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddNodeApiMindmapServiceAddNodePostError = AddNodeApiMindmapServiceAddNodePostErrors[keyof AddNodeApiMindmapServiceAddNodePostErrors];

export type AddNodeApiMindmapServiceAddNodePostResponses = {
    /**
     * Successful Response
     */
    200: NodeDto;
};

export type AddNodeApiMindmapServiceAddNodePostResponse = AddNodeApiMindmapServiceAddNodePostResponses[keyof AddNodeApiMindmapServiceAddNodePostResponses];

export type UpdateNodeApiMindmapServiceUpdateNodePostData = {
    body: MindmapServiceUpdateNodeRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/update_node';
};

export type UpdateNodeApiMindmapServiceUpdateNodePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateNodeApiMindmapServiceUpdateNodePostError = UpdateNodeApiMindmapServiceUpdateNodePostErrors[keyof UpdateNodeApiMindmapServiceUpdateNodePostErrors];

export type UpdateNodeApiMindmapServiceUpdateNodePostResponses = {
    /**
     * Successful Response
     */
    200: NodeDto;
};

export type UpdateNodeApiMindmapServiceUpdateNodePostResponse = UpdateNodeApiMindmapServiceUpdateNodePostResponses[keyof UpdateNodeApiMindmapServiceUpdateNodePostResponses];

export type SetNodeCollapsedApiMindmapServiceSetNodeCollapsedPostData = {
    body: MindmapServiceSetNodeCollapsedRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/set_node_collapsed';
};

export type SetNodeCollapsedApiMindmapServiceSetNodeCollapsedPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetNodeCollapsedApiMindmapServiceSetNodeCollapsedPostError = SetNodeCollapsedApiMindmapServiceSetNodeCollapsedPostErrors[keyof SetNodeCollapsedApiMindmapServiceSetNodeCollapsedPostErrors];

export type SetNodeCollapsedApiMindmapServiceSetNodeCollapsedPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type SetNodeCollapsedApiMindmapServiceSetNodeCollapsedPostResponse = SetNodeCollapsedApiMindmapServiceSetNodeCollapsedPostResponses[keyof SetNodeCollapsedApiMindmapServiceSetNodeCollapsedPostResponses];

export type MoveNodeApiMindmapServiceMoveNodePostData = {
    body: MindmapServiceMoveNodeRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/move_node';
};

export type MoveNodeApiMindmapServiceMoveNodePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MoveNodeApiMindmapServiceMoveNodePostError = MoveNodeApiMindmapServiceMoveNodePostErrors[keyof MoveNodeApiMindmapServiceMoveNodePostErrors];

export type MoveNodeApiMindmapServiceMoveNodePostResponses = {
    /**
     * Successful Response
     */
    200: NodeDto;
};

export type MoveNodeApiMindmapServiceMoveNodePostResponse = MoveNodeApiMindmapServiceMoveNodePostResponses[keyof MoveNodeApiMindmapServiceMoveNodePostResponses];

export type DeleteNodeApiMindmapServiceDeleteNodePostData = {
    body: MindmapServiceDeleteNodeRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/delete_node';
};

export type DeleteNodeApiMindmapServiceDeleteNodePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteNodeApiMindmapServiceDeleteNodePostError = DeleteNodeApiMindmapServiceDeleteNodePostErrors[keyof DeleteNodeApiMindmapServiceDeleteNodePostErrors];

export type DeleteNodeApiMindmapServiceDeleteNodePostResponses = {
    /**
     * Response Delete Node Api Mindmap Service Delete Node Post
     *
     * Successful Response
     */
    200: boolean;
};

export type DeleteNodeApiMindmapServiceDeleteNodePostResponse = DeleteNodeApiMindmapServiceDeleteNodePostResponses[keyof DeleteNodeApiMindmapServiceDeleteNodePostResponses];

export type DeleteMapApiMindmapServiceDeleteMapPostData = {
    body: MindmapServiceDeleteMapRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/delete_map';
};

export type DeleteMapApiMindmapServiceDeleteMapPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMapApiMindmapServiceDeleteMapPostError = DeleteMapApiMindmapServiceDeleteMapPostErrors[keyof DeleteMapApiMindmapServiceDeleteMapPostErrors];

export type DeleteMapApiMindmapServiceDeleteMapPostResponses = {
    /**
     * Response Delete Map Api Mindmap Service Delete Map Post
     *
     * Successful Response
     */
    200: boolean;
};

export type DeleteMapApiMindmapServiceDeleteMapPostResponse = DeleteMapApiMindmapServiceDeleteMapPostResponses[keyof DeleteMapApiMindmapServiceDeleteMapPostResponses];

export type RestoreRevisionApiMindmapServiceRestoreRevisionPostData = {
    body: MindmapServiceRestoreRevisionRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/restore_revision';
};

export type RestoreRevisionApiMindmapServiceRestoreRevisionPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RestoreRevisionApiMindmapServiceRestoreRevisionPostError = RestoreRevisionApiMindmapServiceRestoreRevisionPostErrors[keyof RestoreRevisionApiMindmapServiceRestoreRevisionPostErrors];

export type RestoreRevisionApiMindmapServiceRestoreRevisionPostResponses = {
    /**
     * Successful Response
     */
    200: MapDetail;
};

export type RestoreRevisionApiMindmapServiceRestoreRevisionPostResponse = RestoreRevisionApiMindmapServiceRestoreRevisionPostResponses[keyof RestoreRevisionApiMindmapServiceRestoreRevisionPostResponses];

export type ExpandAllApiMindmapServiceExpandAllPostData = {
    body: MindmapServiceExpandAllRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/expand_all';
};

export type ExpandAllApiMindmapServiceExpandAllPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExpandAllApiMindmapServiceExpandAllPostError = ExpandAllApiMindmapServiceExpandAllPostErrors[keyof ExpandAllApiMindmapServiceExpandAllPostErrors];

export type ExpandAllApiMindmapServiceExpandAllPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ExpandAllApiMindmapServiceExpandAllPostResponse = ExpandAllApiMindmapServiceExpandAllPostResponses[keyof ExpandAllApiMindmapServiceExpandAllPostResponses];

export type SetFoldLevelApiMindmapServiceSetFoldLevelPostData = {
    body: MindmapServiceSetFoldLevelRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/set_fold_level';
};

export type SetFoldLevelApiMindmapServiceSetFoldLevelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetFoldLevelApiMindmapServiceSetFoldLevelPostError = SetFoldLevelApiMindmapServiceSetFoldLevelPostErrors[keyof SetFoldLevelApiMindmapServiceSetFoldLevelPostErrors];

export type SetFoldLevelApiMindmapServiceSetFoldLevelPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type SetFoldLevelApiMindmapServiceSetFoldLevelPostResponse = SetFoldLevelApiMindmapServiceSetFoldLevelPostResponses[keyof SetFoldLevelApiMindmapServiceSetFoldLevelPostResponses];

export type ApplyOutlineApiMindmapServiceApplyOutlinePostData = {
    body: MindmapServiceApplyOutlineRequest;
    path?: never;
    query?: never;
    url: '/api/mindmap_service/apply_outline';
};

export type ApplyOutlineApiMindmapServiceApplyOutlinePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApplyOutlineApiMindmapServiceApplyOutlinePostError = ApplyOutlineApiMindmapServiceApplyOutlinePostErrors[keyof ApplyOutlineApiMindmapServiceApplyOutlinePostErrors];

export type ApplyOutlineApiMindmapServiceApplyOutlinePostResponses = {
    /**
     * Successful Response
     */
    200: MapDetail;
};

export type ApplyOutlineApiMindmapServiceApplyOutlinePostResponse = ApplyOutlineApiMindmapServiceApplyOutlinePostResponses[keyof ApplyOutlineApiMindmapServiceApplyOutlinePostResponses];

export type GraphiqlGraphqlGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/graphql';
};

export type GraphiqlGraphqlGetResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type GraphiqlGraphqlGetResponse = GraphiqlGraphqlGetResponses[keyof GraphiqlGraphqlGetResponses];

export type GraphqlEndpointGraphqlPostData = {
    body: GraphQlRequest;
    path?: never;
    query?: never;
    url: '/graphql';
};

export type GraphqlEndpointGraphqlPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GraphqlEndpointGraphqlPostError = GraphqlEndpointGraphqlPostErrors[keyof GraphqlEndpointGraphqlPostErrors];

export type GraphqlEndpointGraphqlPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GraphqlSchemaSchemaGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/schema';
};

export type GraphqlSchemaSchemaGetResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type GraphqlSchemaSchemaGetResponse = GraphqlSchemaSchemaGetResponses[keyof GraphqlSchemaSchemaGetResponses];

export type ChatArchivesApiChatArchivesGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Map Id
         */
        map_id: number;
    };
    url: '/api/chat/archives';
};

export type ChatArchivesApiChatArchivesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatArchivesApiChatArchivesGetError = ChatArchivesApiChatArchivesGetErrors[keyof ChatArchivesApiChatArchivesGetErrors];

export type ChatArchivesApiChatArchivesGetResponses = {
    /**
     * Response Chat Archives Api Chat Archives Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type ChatArchivesApiChatArchivesGetResponse = ChatArchivesApiChatArchivesGetResponses[keyof ChatArchivesApiChatArchivesGetResponses];

export type ChatArchiveDetailApiChatArchivesArchiveIdGetData = {
    body?: never;
    path: {
        /**
         * Archive Id
         */
        archive_id: string;
    };
    query: {
        /**
         * Map Id
         */
        map_id: number;
    };
    url: '/api/chat/archives/{archive_id}';
};

export type ChatArchiveDetailApiChatArchivesArchiveIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatArchiveDetailApiChatArchivesArchiveIdGetError = ChatArchiveDetailApiChatArchivesArchiveIdGetErrors[keyof ChatArchiveDetailApiChatArchivesArchiveIdGetErrors];

export type ChatArchiveDetailApiChatArchivesArchiveIdGetResponses = {
    /**
     * Response Chat Archive Detail Api Chat Archives  Archive Id  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ChatArchiveDetailApiChatArchivesArchiveIdGetResponse = ChatArchiveDetailApiChatArchivesArchiveIdGetResponses[keyof ChatArchiveDetailApiChatArchivesArchiveIdGetResponses];

export type ChatStatusApiChatStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/chat/status';
};

export type ChatStatusApiChatStatusGetResponses = {
    /**
     * Response Chat Status Api Chat Status Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ChatStatusApiChatStatusGetResponse = ChatStatusApiChatStatusGetResponses[keyof ChatStatusApiChatStatusGetResponses];
